<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Automation Test Report" duration-ms="99348" started-at="2019-10-04T03:13:06Z" finished-at="2019-10-04T03:14:45Z">
    <groups>
    </groups>
    <test name="Automation Test Report" duration-ms="99348" started-at="2019-10-04T03:13:06Z" finished-at="2019-10-04T03:14:45Z">
      <class name="com.ibm.testautomation.testrunner.TestRunner">
        <test-method status="PASS" signature="setUpClass()[pri:0, instance:com.ibm.testautomation.testrunner.TestRunner@1753acfe]" name="setUpClass" is-config="true" duration-ms="147" started-at="2019-10-04T03:13:06Z" finished-at="2019-10-04T03:13:06Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpClass -->
        <test-method status="FAIL" signature="feature(cucumber.api.testng.PickleEventWrapper, cucumber.api.testng.CucumberFeatureWrapper)[pri:0, instance:com.ibm.testautomation.testrunner.TestRunner@1753acfe]" name="feature" duration-ms="98928" started-at="2019-10-04T03:13:06Z" data-provider="features" finished-at="2019-10-04T03:14:45Z">
          <params>
            <param index="0">
              <value>
                <![CDATA["Verify MyJuniper Application"]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA["MyJuniper Application Flow Check"]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.fail(Assert.java:103)
at com.ibm.testautomation.stepdef.MyJuniperStepDef.verify_all_mnadatory_parent_tabs_are_present(MyJuniperStepDef.java:166)
at âœ½.Verify All Mandatory Parent Tabs are present(src/test/java/Features/MyJuniper.feature:9)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- feature -->
        <test-method status="SKIP" signature="tearDownClass()[pri:0, instance:com.ibm.testautomation.testrunner.TestRunner@1753acfe]" name="tearDownClass" is-config="true" duration-ms="0" started-at="2019-10-04T03:14:45Z" finished-at="2019-10-04T03:14:45Z">
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[Skipped after failure. See parameter [skipAfterFailureCount] in surefire or failsafe plugin.]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: Skipped after failure. See parameter [skipAfterFailureCount] in surefire or failsafe plugin.
at org.apache.maven.surefire.testng.utils.FailFastNotifier.beforeInvocation(FailFastNotifier.java:42)
at org.testng.internal.invokers.InvokedMethodListenerInvoker$InvokeBeforeInvocationWithoutContextStrategy.callMethod(InvokedMethodListenerInvoker.java:84)
at org.testng.internal.invokers.InvokedMethodListenerInvoker.invokeListener(InvokedMethodListenerInvoker.java:62)
at org.testng.internal.Invoker.runInvokedMethodListeners(Invoker.java:493)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:443)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
at org.testng.internal.TestMethodWorker.invokeAfterClassMethods(TestMethodWorker.java:214)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:383)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:344)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:125)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:417)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownClass -->
      </class> <!-- com.ibm.testautomation.testrunner.TestRunner -->
    </test> <!-- Automation Test Report -->
  </suite> <!-- Automation Test Report -->
</testng-results>
